name:                sc2hs
version:             0.1.0.0
github:              "githubuser/sc2hs-stack"
license:             BSD3
author:              "kubi"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sc2hs-stack#readme>

dependencies:
- base >= 4.12
- websockets >= 0.12.7.3
- proto-lens
- microlens
- text
- directory
- bytestring
- filepath
- sc2-proto
- process
- mtl
- conduit
- vector
- containers
- unordered-containers
- hashable
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -XOverloadedStrings

library:
  source-dirs: src

executables:
  sc2hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sc2hs
    - transformers
    - safe

tests:
  sc2hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - sc2hs
