name: sc2-proto
version: 0.1.0.2
synopsis: A protocol buffer model for the Starcraft II bot API
maintainer: Sophie Taylor <sophie@spacekitteh.moe>
license: MIT
category: Proto
extra-source-files:
  - protos/s2clientprotocol/*.proto

build-type: Custom
custom-setup:
  dependencies:
    - base
    - Cabal
    - filepath
    - proto-lens-protoc
    - proto-lens-setup

dependencies:
  - base
  - filepath
  - proto-lens-runtime
  

library:
  #source-dirs:      .
  build-tool-depends : proto-lens-protoc:proto-lens-protoc
  #build-tools: proto-lens-protoc:proto-lens-protoc
  #system-build-tools:
  #  - protoc
  generated-other-modules:
    - Paths_sc2_proto
  generated-exposed-modules:
    - Proto.S2clientprotocol.Common
    - Proto.S2clientprotocol.Data
    - Proto.S2clientprotocol.Debug
    - Proto.S2clientprotocol.Error
    - Proto.S2clientprotocol.Query
    - Proto.S2clientprotocol.Raw
    - Proto.S2clientprotocol.Sc2api
    - Proto.S2clientprotocol.Score
    - Proto.S2clientprotocol.Spatial
    - Proto.S2clientprotocol.Ui
    - Proto.S2clientprotocol.Common_Fields
    - Proto.S2clientprotocol.Data_Fields
    - Proto.S2clientprotocol.Debug_Fields
    - Proto.S2clientprotocol.Error_Fields
    - Proto.S2clientprotocol.Query_Fields
    - Proto.S2clientprotocol.Raw_Fields
    - Proto.S2clientprotocol.Sc2api_Fields
    - Proto.S2clientprotocol.Score_Fields
    - Proto.S2clientprotocol.Spatial_Fields
    - Proto.S2clientprotocol.Ui_Fields
