module SC2.Ids.UpgradeResearchedFrom where

-- | Copied from https://github.com/BurnySc2/python-sc2/blob/15fbac3f2645cc2641ce9a56d481f1f7a7f2a814/sc2/dicts/upgrade_researched_from.py#L10

import SC2.Ids.UpgradeId
import SC2.Ids.UnitTypeId

import Data.HashMap.Strict as HashMap


upgradeDeps :: HashMap UpgradeId UnitTypeId
upgradeDeps = HashMap.fromList
    [ (Adeptpiercingattack, ProtossTwilightcouncil),
    -- (ANABOLICSYNTHESIS, ZergUltraliskcavern),
    (Bansheecloak, TerranStarporttechlab),
    (Bansheespeed, TerranStarporttechlab),
    (Battlecruiserenablespecializations, TerranFusioncore),
    (Blinktech, ProtossTwilightcouncil),
    (Burrow, ZergHatchery),
    (Centrificalhooks, ZergBanelingnest),
    (Charge, ProtossTwilightcouncil),
    (Chitinousplating, ZergUltraliskcavern),
    (Cyclonelockondamageupgrade, TerranFactorytechlab),
    (Darktemplarblinkupgrade, ProtossDarkshrine),
    -- (DIGGINGCLAWS, ZergLurkerdenmp),
    (Drillclaws, TerranFactorytechlab),
    (Evolvegroovedspines, ZergHydraliskden),
    (Evolvemuscularaugments, ZergHydraliskden),
    (Extendedthermallance, ProtossRoboticsbay),

    (Glialreconstitution, ZergRoachwarren),
    (Graviticdrive, ProtossRoboticsbay),
    (Highcapacitybarrels, TerranFactorytechlab),
    (Hisecautotracking, TerranEngineeringbay),
    -- (INTERFERENCEMATRIX, TerranStarporttechlab),
    (Liberatoragrangeupgrade, TerranFusioncore),
    -- (LURKERRANGE, LURKERDENMP),
    (Medivacincreasespeedboost, TerranFusioncore),
    (Neuralparasite, ZergInfestationpit),
    (Observergraviticbooster, ProtossRoboticsbay),
    (Overlordspeed, ZergHatchery),
    (Personalcloaking, TerranGhostacademy),
    (Phoenixrangeupgrade, ProtossFleetbeacon),
    (Protossairarmorslevel1, ProtossCyberneticscore),
    (Protossairarmorslevel2, ProtossCyberneticscore),
    (Protossairarmorslevel3, ProtossCyberneticscore),
    (Protossairweaponslevel1, ProtossCyberneticscore),
    (Protossairweaponslevel2, ProtossCyberneticscore),
    (Protossairweaponslevel3, ProtossCyberneticscore),
    (Protossgroundarmorslevel1, ProtossForge),
    (Protossgroundarmorslevel2, ProtossForge),
    (Protossgroundarmorslevel3, ProtossForge),
    (Protossgroundweaponslevel1, ProtossForge),
    (Protossgroundweaponslevel2, ProtossForge),
    (Protossgroundweaponslevel3, ProtossForge),
    (Protossshieldslevel1, ProtossForge),
    (Protossshieldslevel2, ProtossForge),
    (Protossshieldslevel3, ProtossForge),
    (Psistormtech, ProtossTemplararchive),
    (Punishergrenades, TerranBarrackstechlab),
    (Shieldwall, TerranBarrackstechlab),
    (Smartservos, TerranFactorytechlab),
    (Stimpack, TerranBarrackstechlab),
    -- (TEMPESTGROUNDATTACKUPGRADE, ProtossFleetbeacon),
    (Terranbuildingarmor, TerranEngineeringbay),
    (Terraninfantryarmorslevel1, TerranEngineeringbay),
    (Terraninfantryarmorslevel2, TerranEngineeringbay),
    (Terraninfantryarmorslevel3, TerranEngineeringbay),
    (Terraninfantryweaponslevel1, TerranEngineeringbay),
    (Terraninfantryweaponslevel2, TerranEngineeringbay),
    (Terraninfantryweaponslevel3, TerranEngineeringbay),
    (Terranshipweaponslevel1, TerranArmory),
    (Terranshipweaponslevel2, TerranArmory),
    (Terranshipweaponslevel3, TerranArmory),
    (Terranvehicleandshiparmorslevel1, TerranArmory),
    (Terranvehicleandshiparmorslevel2, TerranArmory),
    (Terranvehicleandshiparmorslevel3, TerranArmory),
    (Terranvehicleweaponslevel1, TerranArmory),
    (Terranvehicleweaponslevel2, TerranArmory),
    (Terranvehicleweaponslevel3, TerranArmory),
    (Tunnelingclaws, ZergRoachwarren),
    -- (VOIDRAYSPEEDUPGRADE, ProtossFleetbeacon),
    (Warpgateresearch, ProtossCyberneticscore),
    (Zergflyerarmorslevel1, ZergSpire),
    (Zergflyerarmorslevel2, ZergSpire),
    (Zergflyerarmorslevel3, ZergSpire),
    (Zergflyerweaponslevel1, ZergSpire),
    (Zergflyerweaponslevel2, ZergSpire),
    (Zergflyerweaponslevel3, ZergSpire),
    (Zerggroundarmorslevel1, ZergEvolutionchamber),
    (Zerggroundarmorslevel2, ZergEvolutionchamber),
    (Zerggroundarmorslevel3, ZergEvolutionchamber),
    (Zerglingattackspeed, ZergSpawningpool),
    (Zerglingmovementspeed, ZergSpawningpool),
    (Zergmeleeweaponslevel1, ZergEvolutionchamber),
    (Zergmeleeweaponslevel2, ZergEvolutionchamber),
    (Zergmeleeweaponslevel3, ZergEvolutionchamber),
    (Zergmissileweaponslevel1, ZergEvolutionchamber),
    (Zergmissileweaponslevel2, ZergEvolutionchamber),
    (Zergmissileweaponslevel3, ZergEvolutionchamber)
    ]

    -- (FRENZY, ZergHydraliskden),
--     (GLIALRECONSTITUTION, ZergRoachwarren),
--     (GRAVITICDRIVE, ProtossRoboticsbay),
--     (HIGHCAPACITYBARRELS, TerranFactorytechlab),
--     (HISECAUTOTRACKING, TerranEngineeringbay),
--     (INTERFERENCEMATRIX, TerranStarporttechlab),
--     (LIBERATORAGRANGEUPGRADE, TerranFusioncore),
--     (LURKERRANGE, LURKERDENMP),
--     (MEDIVACCADUCEUSREACTOR, TerranFusioncore),
--     (NEURALPARASITE, INFESTATIONPIT),
--     (OBSERVERGRAVITICBOOSTER, ProtossRoboticsbay),
--     (OVERLORDSPEED, ZergHatchery),
--     (PERSONALCLOAKING, GHOSTACADEMY),
--     (PHOENIXRANGEUPGRADE, ProtossFleetbeacon),
--     (PROTOSSAIRARMORSLEVEL1, ProtossCyberneticscore),
--     (PROTOSSAIRARMORSLEVEL2, ProtossCyberneticscore),
--     (PROTOSSAIRARMORSLEVEL3, ProtossCyberneticscore),
--     (PROTOSSAIRWEAPONSLEVEL1, ProtossCyberneticscore),
--     (PROTOSSAIRWEAPONSLEVEL2, ProtossCyberneticscore),
--     (PROTOSSAIRWEAPONSLEVEL3, ProtossCyberneticscore),
--     (PROTOSSGROUNDARMORSLEVEL1, ProtossForge),
--     (PROTOSSGROUNDARMORSLEVEL2, ProtossForge),
--     (PROTOSSGROUNDARMORSLEVEL3, ProtossForge),
--     (PROTOSSGROUNDWEAPONSLEVEL1, ProtossForge),
--     (PROTOSSGROUNDWEAPONSLEVEL2, ProtossForge),
--     (PROTOSSGROUNDWEAPONSLEVEL3, ProtossForge),
--     (PROTOSSSHIELDSLEVEL1, ProtossForge),
--     (PROTOSSSHIELDSLEVEL2, ProtossForge),
--     (PROTOSSSHIELDSLEVEL3, ProtossForge),
--     (PSISTORMTECH, ProtossTemplararchive),
--     (PUNISHERGRENADES, TerranBarrackstechlab),
--     (SHIELDWALL, TerranBarrackstechlab),
--     (SMARTSERVOS, TerranFactorytechlab),
--     (STIMPACK, TerranBarrackstechlab),
--     (TEMPESTGROUNDATTACKUPGRADE, ProtossFleetbeacon),
--     (TERRANBUILDINGARMOR, TerranEngineeringbay),
--     (TERRANINFANTRYARMORSLEVEL1, TerranEngineeringbay),
--     (TERRANINFANTRYARMORSLEVEL2, TerranEngineeringbay),
--     (TERRANINFANTRYARMORSLEVEL3, TerranEngineeringbay),
--     (TERRANINFANTRYWEAPONSLEVEL1, TerranEngineeringbay),
--     (TERRANINFANTRYWEAPONSLEVEL2, TerranEngineeringbay),
--     (TERRANINFANTRYWEAPONSLEVEL3, TerranEngineeringbay),
--     (TERRANSHIPWEAPONSLEVEL1, TerranArmory),
--     (TERRANSHIPWEAPONSLEVEL2, TerranArmory),
--     (TERRANSHIPWEAPONSLEVEL3, TerranArmory),
--     (TERRANVEHICLEANDSHIPARMORSLEVEL1, TerranArmory),
--     (TERRANVEHICLEANDSHIPARMORSLEVEL2, TerranArmory),
--     (TERRANVEHICLEANDSHIPARMORSLEVEL3, TerranArmory),
--     (TERRANVEHICLEWEAPONSLEVEL1, TerranArmory),
--     (TERRANVEHICLEWEAPONSLEVEL2, TerranArmory),
--     (TERRANVEHICLEWEAPONSLEVEL3, TerranArmory),
--     (TUNNELINGCLAWS, ZergRoachwarren),
--     (VOIDRAYSPEEDUPGRADE, ProtossFleetbeacon),
--     (WARPGATERESEARCH, ProtossCyberneticscore),
--     (ZERGFLYERARMORSLEVEL1, ZergSpire),
--     (ZERGFLYERARMORSLEVEL2, ZergSpire),
--     (ZERGFLYERARMORSLEVEL3, ZergSpire),
--     (ZERGFLYERWEAPONSLEVEL1, ZergSpire),
--     (ZERGFLYERWEAPONSLEVEL2, ZergSpire),
--     (ZERGFLYERWEAPONSLEVEL3, ZergSpire),
--     (ZERGGROUNDARMORSLEVEL1, ZergEvolutionchamber),
--     (ZERGGROUNDARMORSLEVEL2, ZergEvolutionchamber),
--     (ZERGGROUNDARMORSLEVEL3, ZergEvolutionchamber),
--     (ZERGLINGATTACKSPEED, ZergSpawningpool),
--     (ZERGLINGMOVEMENTSPEED, ZergSpawningpool),
--     (ZERGMELEEWEAPONSLEVEL1, ZergEvolutionchamber),
--     (ZERGMELEEWEAPONSLEVEL2, ZergEvolutionchamber),
--     (ZERGMELEEWEAPONSLEVEL3, ZergEvolutionchamber),
--     (ZERGMISSILEWEAPONSLEVEL1, ZergEvolutionchamber),
--     (ZERGMISSILEWEAPONSLEVEL2, ZergEvolutionchamber),
--     (ZERGMISSILEWEAPONSLEVEL3, ZergEvolutionchamber),
-- ]