name:                lambdarookie01
version:             0.0.4.0
license:             MIT
author:              "kubi"

description: >
  Protoss bot implementation using sc2api and sc2monad

dependencies:
  - base >= 4.12
  - sc2api
  - sc2monad
  - proto-lens
  - microlens
  - text
  - containers
  - unordered-containers
  - hashable
  - safe
  - random
  - conduit
  - split
  - transformers
  - mtl

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - OverloadedLabels
  - ImportQualifiedPost

executables:
  lambdarookie01:
    main: Main.hs
    source-dirs:
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
